spring:
  application:
    name: cloud-gateway
    #加载环境配置，路由配置，跨域配置
  profiles:
    active: route,cors
  cloud:
    gateway:
      #通过服务名称访问微服务
      discovery:
        locator:
          enabled: true
server:
  port: 86
#服务注册中心地址
eureka:
  client:
    service-url:
      defaultZone: http://localhost:81/eureka/
---
spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      routes:
        - id: service-user
          uri: lb://SERVICE-USER
          predicates:
            - Path=/api/user/**
          filters:
            #去掉前缀的个数
            - StripPrefix=1
        - id: service-order
          uri: lb://SERVICE-ORDER
          predicates:
            - Path=/api/orders/**
          filters:
              #去掉前缀的个数
            - StripPrefix=1
  profiles: route


---
spring:
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            # 允许携带认证信息
            # 允许跨域的源(网站域名/ip)，设置*为全部
            # 允许跨域请求里的head字段，设置*为全部
            # 允许跨域的method， 默认为GET和OPTIONS，设置*为全部
            # 跨域允许的有效期
            allow-credentials: true
            allowed-origins: "*"
            #- "http://localhost:8080"
            #- "http://localhost:13010"
            allowed-headers: "*"
            allowed-methods:
              - OPTIONS
              - GET
              - POST
            max-age: 3600
  profiles: cors
